name: Find encrypted files
description: Find encrypted files in the repository.

outputs:
  files:
    description: The list of encrypted files in the repository. Space separated.
    value: ${{ steps.compute.outputs.files }}

runs:
  using: composite
  steps:
  - id: compute
    name: Compute files list
    run: |
      FILES=""
      for file in $(find . -name .env); do FILES+="$file;"; done
      echo "Files: $FILES"
      echo "files=${FILES%?}" >> $GITHUB_OUTPUT
    shell: bash
