name: Find encrypted files
description: Find encrypted files in the repository.

runs:
  using: composite
  steps:
  - run: ${{ github.action_path }}/find-encrypted-files.sh
    id: compute
    shell: bash
